### PR TITLE
Finetuned colors to better match the official vals

### PR DESCRIPTION
**Pull request by blacksails**
Also includes orange as bright red.
And the comment color as bright blue.

Please check this out and see if you don't find it a bit better. I would surely prefer to have access to accurate values of all the dracula colors within the 16 ANSI colors.

### CODE REVIEW

**Comment by nesl247** [comment]
I'm not a fan of the changes personally. For example, when using fish-shell, when you type an invalid command it's red currently, which makes sense, but turns orange with these changes. Other places that used a nice purple are now using a blue that is hard to see against the background.

**Comment by blacksails** [comment]
@nesl247 do you have another suggestion of how to get the orange and the comment color into the 16 ANSI colors?

**Comment by blacksails** [comment]
The official solarized theme is implemented like this.
screen shot 2016-05-22 at 21 30 17

I found inspiration here.

**Comment by blacksails** [comment]
I want to improve the vim theme so that it can optionally use the precise colors provided by the 16 ANSI colors. Which is why i would like to have access to all of the colors here. Thats how the solarized theme works.

**Comment by nesl247** [comment]
I'm just commenting as a user of the theme. I'm not the maintainer. I personally don't wish to see it changed from the way it is as it's pretty perfect to me. But if it needs to be changed, I can always continue to use it as it is today.

**Comment by blacksails** [comment]
Maybe it would make more sense to move the comment color to bright magenta, as that color is less frequently used.

**Comment by blacksails** [comment]
@nesl247 Shouldn't you be able to configure fish-shell to use the normal red color?

**Comment by blacksails** [comment]
The orange could also be moved to bright yellow.

**Comment by nesl247** [comment]
You're right, I just forgot about it since I've been using the dracula iTerm theme forever.

**Comment by nesl247** [comment]
@blacksails I'd like to see the theme with those ideas you mentioned. FYI, I noticed your screenshot looks like iTerm2. You might want to consider upgrading to the iTerm2/3 (Whatever it's being called) beta. It looks a lot nicer in 10.10+, and has some nice integrations and such.

**Comment by blacksails** [comment]
@nesl247 Ah haven't heard of the new version. Thanks! I will check it out later today. 👍

**Comment by nesl247** [comment]
@blacksails Just seeing if you've had a chance to work on this at all?

**Comment by blacksails** [comment]
@nesl247 unfortunately not. You can just close the issue, i have gone back to my beloved solarized. I have found that dracula has too few colors for me. GL with the project i might be back some day :)

**Comment by nesl247** [comment]
Thanks for giving it a shot for a while :)

**Pull request closed without merging**
